name: Test Movie Recommender (no GUI)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run non-GUI test
        run: |
          echo "Testing Movie Recommender core logic..."
          python - <<'EOF'
          import main

          print("✅ main.py imported successfully!")
          print("Se arrivi qui, il codice è valido ma la GUI non è stata avviata.")
          EOF
