name: Run Movie Recommender

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:  # ti permette di avviarlo manualmente da GitHub

jobs:
  run-app:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Clona il repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Imposta Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 3️⃣ Installa le dipendenze
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # 4️⃣ Esegui l'app principale
      - name: Run Movie Recommender
        run: |
          if [ -f main.py ]; then python main.py; elif [ -f app.py ]; then python app.py; else echo "No main script found"; fi
